name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: npm i
      run: npm i
    - name: Release
      run: npm run release

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
