name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules
    - name: npm i
      run: npm i
    - name: Release
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: npm run release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
